package de.jensklingenberg.kt_dart_builder.main.specs

enum class Keyword {
}

val ABSTRACT = "abstract"
val AS = "as"
val AT = "@"
val ASYNC = "async"
val ASYNCStar = "async*"
val AWAIT = "await"
val CLASS = "class"
val CONST = "const"
val DEFERRED = "deferred"
val DYNAMIC = "dynamic"
val EQUAL = "="
val EXPORT = "export"
val EXTENDS = "extends"
val EXTERNAL = "external"
val FACTORY = "factory"
val FINAL = "final"
val FUNCTION = "Function"
val GET = "get"
val GREATER = ">"
val HIDE = "hide"
val IMPLEMENTS = "implements"
val IMPORT = "import"
val LESSER = "<"
val SET = "set"
val RETURN = "return"
val SHOW = "show"
val SPACE = " "
val STATIC = "static"
val SYNCStar = "sync*"
val THIS = "this"
val VAR = "var"
val WITH = "with"
val BOOL = "bool"